name: fsl-challenge
on: [pull_request]
jobs:
  built-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '15'
      - run: npm i
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run lint
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm i -g prettier && npm run prettier
        working-directory: ./codebase/rdicidr-0.1.0
      - run: CI=true npm run test
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run build
        working-directory: ./codebase/rdicidr-0.1.0